# command = "bril2json < {filename} | ../build/fastbrili -p {args}"
command = "bril2json < {filename} | $FASTBRILI -ni -bo byte-out ; cat byte-out | $FASTBRILI -b {args} ; rm byte-out"
output.out = "-"
# output.prof = "2"
