[package]
name = "brilift"
version = "0.1.0"
edition = "2021"

[dependencies]
bril-rs = {path = "../bril-rs"}
cranelift = "0.83.0"
cranelift-object = "0.83.0"
cranelift-module = "0.83.0"
cranelift-native = "0.83.0"
